name: backend

dependencies:
  - python==3.7
  - pip
  - opencv
  - pip:
    - flask
    - Flask-RESTful
    - Flask-SocketIO
    - SQLAlchemy
    - Flask-SQLAlchemy
    - marshmallow-sqlalchemy
    - kombu
    - opencv-python==4.1.1.26
    - numpy
    - eventlet
